// @license
// Copyright (c) 2025 Göran Hegenberg. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:convert';
import 'dart:io';

import 'package:gg_args/gg_args.dart';
import 'package:gg_console_colors/gg_console_colors.dart';
import 'package:gg_log/gg_log.dart';
import 'package:gg_process/gg_process.dart';
import 'package:gg_status_printer/gg_status_printer.dart';
import 'package:gg_test/gg_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:path/path.dart';

typedef _Report = Map<String, Map<int, int>>;
typedef _MissingLines = Map<String, List<int>>;
typedef _TaskResult = (int, List<String>, List<String>);

// #############################################################################

/// Runs TypeScript tests (e.g. via `npm test`) and validates 100%
/// coverage for all relevant source files.
///
/// The command expects a typical TypeScript project layout with
///
/// * implementation files in `src/`
/// * corresponding test files in `test/` with the pattern
///   `src/foo.ts` → `test/foo.spec.ts`
/// * an `lcov.info` report in `coverage/lcov.info` (e.g. generated by
///   Jest with `--coverage`).
class TestsTs extends DirCommand<void> {
  /// Creates a new [TestsTs] command.
  ///
  /// The [processWrapper] can be overridden in tests to avoid executing
  /// real external commands.
  TestsTs({
    required super.ggLog,
    this.processWrapper = const GgProcessWrapper(),
  }) : super(
         name: 'tests-ts',
         description: 'Runs TypeScript tests with coverage.',
       );

  /// Folders that will be excluded from coverage evaluation.
  static final foldersExcludedFromCoverageTs = <String>[
    'node_modules',
    'dist',
    'build',
    '.git',
  ];

  /// The process wrapper used to execute shell processes.
  final GgProcessWrapper processWrapper;

  final _errors = <String>[];
  final _messages = <String>[];
  late Directory _srcDir;

  final Map<String, List<bool>> _ignoredLinesCache = {};

  // .........................................................................
  @override
  Future<void> get({required Directory directory, required GgLog ggLog}) async {
    await check(directory: directory);

    _srcDir = Directory(join(directory.path, 'src'));

    const packageManager = 'npx vitest';

    final statusPrinter = GgStatusPrinter<void>(
      message: 'Running "$packageManager"',
      ggLog: ggLog,
    );

    statusPrinter.status = GgStatusPrinterStatus.running;

    final (code, messages, errors) = await _task(directory);
    final success = code == 0;

    statusPrinter.status = success
        ? GgStatusPrinterStatus.success
        : GgStatusPrinterStatus.error;

    if (!success) {
      _logErrors(messages, errors);
    }

    if (code != 0) {
      final command = blue(packageManager);
      throw Exception(
        ['Tests failed', yellow('Run "$command" to see details.')].join('\n'),
      );
    }
  }

  // .........................................................................
  void _logErrors(List<String> messages, List<String> errors) {
    final errorMsg = errors.where((e) => e.isNotEmpty).join('\n');
    final stdoutMsg = messages.where((e) => e.isNotEmpty).join('\n');

    if (errorMsg.isNotEmpty) {
      ggLog(errorMsg); // coverage:ignore-line
    }
    if (stdoutMsg.isNotEmpty) {
      ggLog(stdoutMsg);
    }
  }

  // .........................................................................
  String _addDotSlash(String relativeFile) {
    if (relativeFile.isEmpty) {
      return relativeFile;
    }
    if (!relativeFile.startsWith('./'.os)) {
      return './$relativeFile'.os;
    }
    return relativeFile;
  }

  // .........................................................................
  bool _isExcludedFromCoverageTs(String path) {
    for (final folder in foldersExcludedFromCoverageTs) {
      if (path.contains('/$folder/'.os)) {
        return true;
      }
    }
    return false;
  }

  // .........................................................................
  List<bool> _ignoredLines(String scriptPath) {
    final cachedResult = _ignoredLinesCache[scriptPath];
    if (cachedResult != null) {
      return cachedResult;
    }

    final file = File(scriptPath);
    if (!file.existsSync()) {
      final empty = <bool>[];
      _ignoredLinesCache[scriptPath] = empty;
      return empty;
    }

    final lines = file.readAsLinesSync();
    final ignoredLines = List<bool>.filled(lines.length + 1, false);

    final isExcludedFromCoverage = _isExcludedFromCoverageTs(scriptPath);

    var ignoreRange = false;
    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      final lineNumber = i + 1;

      // Ignore entire file if explicitly requested or folder is excluded.
      if (line.contains('coverage:ignore-file') || isExcludedFromCoverage) {
        ignoredLines.fillRange(0, lines.length + 1, true);
        break;
      }

      if (line.contains('coverage:ignore-start')) {
        ignoreRange = true;
      }

      if (line.contains('coverage:ignore-end')) {
        ignoreRange = false;
      }

      final ignoreLine = line.contains('coverage:ignore-line');
      ignoredLines[lineNumber] = ignoreRange || ignoreLine;
    }

    _ignoredLinesCache[scriptPath] = ignoredLines;
    return ignoredLines;
  }

  // .........................................................................
  _Report _generateReport(Directory dir) {
    final coverageFile = File(join(dir.path, 'coverage', 'lcov.info'));
    if (!coverageFile.existsSync()) {
      return _Report();
    }

    final result = _Report();

    Map<int, int>? summaryForScript;
    var currentScriptKey = '';
    var ignoredLinesForScript = <bool>[];

    final lines = coverageFile.readAsLinesSync();
    for (final line in lines) {
      if (line.startsWith('SF:')) {
        final scriptFromReport = line.replaceFirst('SF:', '').trim();
        final scriptRelative = scriptFromReport.startsWith('.')
            ? scriptFromReport
            : './$scriptFromReport';
        final script = scriptRelative.os;

        final scriptAbsolute = canonicalize(join(dir.path, script));

        summaryForScript = <int, int>{};
        currentScriptKey = scriptAbsolute;
        result[currentScriptKey] = summaryForScript;

        ignoredLinesForScript = _ignoredLines(scriptAbsolute);
      } else if (line.startsWith('DA:') && summaryForScript != null) {
        final parts = line.replaceFirst('DA:', '').split(',');
        if (parts.length != 2) {
          continue;
        }
        final lineNumber = int.parse(parts[0]);
        final rawHits = int.parse(parts[1]);

        final isIgnored =
            lineNumber >= 0 &&
            lineNumber < ignoredLinesForScript.length &&
            ignoredLinesForScript[lineNumber];

        final hits = isIgnored ? 1 : rawHits;
        summaryForScript[lineNumber] = hits;
      }
    }

    return result;
  }

  // .........................................................................
  double _calculateCoverage(_Report report) {
    var totalLines = 0;
    var coveredLines = 0;

    for (final script in report.keys) {
      for (final line in report[script]!.keys) {
        totalLines++;
        if (report[script]![line]! > 0) {
          coveredLines++;
        }
      }
    }

    if (totalLines == 0) {
      return 0;
    }

    final percentage = (coveredLines / totalLines) * 100;
    return percentage;
  }

  // .........................................................................
  _MissingLines _estimateMissingLines(_Report report) {
    final _MissingLines result = {};
    for (final script in report.keys) {
      final lines = report[script]!;
      final linesSorted = lines.keys.toList()..sort();

      for (final line in linesSorted) {
        final hits = lines[line]!;
        if (hits == 0) {
          result[script] ??= <int>[];
          result[script]!.add(line);
        }
      }
    }

    return result;
  }

  // .........................................................................
  void _printMissingLines(_MissingLines missingLines, Directory dir) {
    for (final script in missingLines.keys) {
      final relativeScript = relative(script, from: dir.path);
      final testFileRelative = relativeScript
          .replaceFirst('src/'.os, 'test/'.os)
          .replaceAll('.ts', '.spec.ts');

      const printFirstOnly = true;
      final lineNumbers = missingLines[script]!;
      for (final lineNumber in lineNumbers) {
        final implementationRed = red('$relativeScript:$lineNumber');
        final testFileBlue = blue(testFileRelative);

        _messages.add('- $implementationRed');
        _messages.add('  $testFileBlue');
        if (printFirstOnly) {
          break;
        }
      }
    }
  }

  // .........................................................................
  Iterable<(File, File)> _implementationAndTestFiles() {
    final implementationFiles = _srcDir
        .listSync(recursive: true)
        .whereType<File>()
        .where((file) {
          final path = file.path;
          return path.endsWith('.ts') &&
              !path.endsWith('.d.ts') &&
              !path.contains('/test/'.os) &&
              !path.contains('/node_modules/'.os);
        })
        .toList();

    final result = implementationFiles.map((implementationFile) {
      final relativeImpl = relative(
        implementationFile.path,
        from: _srcDir.path,
      );

      final testFilePath = join(
        _srcDir.parent.path,
        'test',
        relativeImpl.replaceAll('.ts', '.spec.ts'),
      );

      return (implementationFile, File(testFilePath));
    });

    return result;
  }

  // .........................................................................
  Iterable<(File, File)> _collectMissingTestFiles(
    Iterable<(File, File)> files,
  ) => files.where((e) => !e.$2.existsSync());

  // .........................................................................
  void _createMissingTestFiles(
    Iterable<(File, File)> missingFiles,
    Directory dir,
  ) {
    if (missingFiles.isEmpty) {
      return;
    }

    _messages.add(yellow('Tests were created. Please revise:'));

    final packageName = basename(canonicalize(dir.path));

    const testBoilerplate = '''
// @license
// Copyright (c) 2025 Göran Hegenberg. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import { describe, expect, it } from '@jest/globals';
import { CLASSNAME } from '../src/RELATIVE_IMPORT';

describe('CLASSNAME', () => {
  it('example should work', () => {
    const instance = CLASSNAME.example();
    expect(instance).toBeDefined();
  });
});
''';

    for (final (implementationFile, testFile) in missingFiles) {
      final testFileDir = dirname(testFile.path);
      Directory(testFileDir).createSync(recursive: true);

      final className = basenameWithoutExtension(implementationFile.path);
      final relativeImport = relative(
        implementationFile.path,
        from: join(dir.path, 'src'),
      ).replaceAll('\\', '/');

      final content = testBoilerplate
          .replaceAll('CLASSNAME', className)
          .replaceAll('RELATIVE_IMPORT', relativeImport.replaceAll('.ts', ''))
          .replaceFirst(
            "import { describe, expect, it } from '@jest/globals';\n",
            "import { describe, expect, it } from '@jest/globals';\n",
          )
          .replaceFirst(
            "import { CLASSNAME } from '../src/RELATIVE_IMPORT';",
            "import { CLASSNAME } from '../src/RELATIVE_IMPORT';",
          )
          .replaceFirst(
            '// found in the LICENSE file in the root of this package.',
            '// found in the LICENSE file in the root of the $packageName package.',
          );

      testFile.writeAsStringSync(content);

      final relativeTestFile = red(relative(testFile.path, from: dir.path));
      final relativeSrcFile = brightBlack(
        relative(implementationFile.path, from: dir.path),
      );

      _messages.add('- $relativeTestFile\n  $relativeSrcFile');
    }
  }

  // .........................................................................
  Iterable<(File, File)> _findUntestedFiles(
    _Report report,
    Iterable<(File, File)> files,
  ) {
    final result = files.where((e) {
      final implementationPath = e.$1.path;

      for (final reportItem in report.keys) {
        final key = implementationPath;
        if (reportItem.toLowerCase() == key.toLowerCase()) {
          return false;
        }
      }

      final fileContent = File(implementationPath).readAsStringSync();

      final ignoreMissingCoverage =
          fileContent.contains('coverage:ignore-file') ||
          !hasFunctionsTs(fileContent);

      return !ignoreMissingCoverage;
    }).toList();

    return result;
  }

  // .........................................................................
  void _printUntestedFiles(Iterable<(File, File)> files, Directory dir) {
    for (final (implementation, test) in files) {
      final srcFileRelative = blue(
        relative(implementation.path, from: dir.path),
      );
      final testFileRelative = red(relative(test.path, from: dir.path));

      _messages.add('- $testFileRelative');
      _messages.add('  $srcFileRelative');
    }
  }

  // .........................................................................
  Future<int> _testTs(Directory dir) async {
    final process = await processWrapper.start('cmd', [
      '/c',
      'npx vitest run --coverage && npm run lint',
    ], workingDirectory: dir.path);

    final errorLines = <String>{};
    final previousMessagesBelongingToError = <String>[];
    var isError = false;

    await _processTestOutput(
      process,
      isError,
      previousMessagesBelongingToError,
      errorLines,
    );

    final exitCode = await process.exitCode;

    return exitCode != 0 || errorLines.isNotEmpty ? 1 : 0;
  }

  // .........................................................................
  Future<void> _processTestOutput(
    Process process,
    bool isError,
    List<String> previousMessagesBelongingToError,
    Set<String> errorLines,
  ) async {
    void collectEvent(String event) {
      // Jest uses "FAIL" to indicate failing test suites.
      isError = isError || event.toLowerCase().contains('fail');
      if (isError) {
        event = ErrorInfoReaderTs().makeVscodeCompatible(event);
        previousMessagesBelongingToError.add(event);
      }

      final newErrorLines = ErrorInfoReaderTs().extractErrorLines(event);

      if (newErrorLines.isNotEmpty &&
          !errorLines.contains(newErrorLines.first)) {
        final newErrorLinesString = red(
          _addDotSlash(newErrorLines.join(',\n   ')),
        );
        _messages.add(' - $newErrorLinesString');

        final cleanedMessage = ErrorInfoReaderTs().cleanupTestErrors(
          previousMessagesBelongingToError,
        );
        for (final message in cleanedMessage) {
          _messages.add(brightBlack(message));
        }

        isError = false;
      }
      errorLines.addAll(newErrorLines);
    }

    final stdoutFuture = process.stdout
        .transform(utf8.decoder)
        .forEach(collectEvent);

    final stderrFuture = process.stderr
        .transform(utf8.decoder)
        .forEach(collectEvent);

    await Future.wait([stdoutFuture, stderrFuture]);
  }

  // .........................................................................
  Future<_TaskResult> _task(Directory dir) async {
    final files = _implementationAndTestFiles();

    final missingTestFiles = _collectMissingTestFiles(files);
    if (missingTestFiles.isNotEmpty) {
      _createMissingTestFiles(missingTestFiles, dir);
      return (1, _messages, _errors);
    }

    final error = await _testTs(dir);
    if (error != 0) {
      return (error, _messages, _errors);
    }

    final report = _generateReport(dir);

    final untestedFiles = _findUntestedFiles(report, files);
    if (untestedFiles.isNotEmpty) {
      _messages.add(yellow('Please add valid tests to the following files:'));
      _printUntestedFiles(untestedFiles, dir);
      return (1, _messages, _errors);
    }

    final percentage = _calculateCoverage(report);

    if (percentage != 100.0) {
      _messages.add(yellow('Coverage not 100%. Untested code:'));
      final missingLines = percentage < 100.0
          ? _estimateMissingLines(report)
          : _MissingLines();
      _printMissingLines(missingLines, dir);
      return (1, _messages, _errors);
    } else {
      _messages.add('✅ Coverage is 100%!');
      return (error, _messages, _errors);
    }
  }
}

// ............................................................................
/// Mocktail mock for [TestsTs].
class MockTestsTs extends Mock implements TestsTs {}
