name: gg_test
description: gg_test is a powerful testing package designed to enhance the Flutter and Dart development experience.
version: 1.0.18
repository: https://github.com/inlavigo/gg_test.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^2.0.1
  gg_console_colors: ^2.0.2
  gg_is_flutter: ^1.0.0
  gg_is_github: ^1.0.1
  gg_log: ^1.0.0
  gg_process: ^1.0.7
  gg_status_printer: ^1.0.5
  mocktail: ^1.0.3
  path: ^1.8.0
  recase: ^4.1.0

dev_dependencies:
  gg_capture_print: ^1.0.3
  lints: ^3.0.0
  test: ^1.24.0